### ISSUE TITLE
Run Containers example 1 fails with code traceback

### ISSUE THREAD

**Issue by estahlberg** [JDACS4C-IMPROVE/docs#2]
I've tried example 1 in the Run Containers documentation and it doesn't appear to now work successfully. 
What is needed to get this to run? 

ac.estahlberg@lambda0:~/IMPROVEDIR$ singularity exec --nv --bind $HOME/IMPROVEDIR:/candle_data_dir /software/improve/images/GraphDRP:0.0.1-20221109.sif train.sh 2 /candle_data_dir GraphDRP/graphdrp_default_model.txt

CMD = python /usr/local/GraphDRP/graphdrp_baseline_pytorch.py --config_file GraphDRP/graphdrp_default_model.txt
using CUDA_VISIBLE_DEVICES 2
using CANDLE_DATA_DIR /candle_data_dir
using CANDLE_CONFIG GraphDRP/graphdrp_default_model.txt
running command python /usr/local/GraphDRP/graphdrp_baseline_pytorch.py --config_file GraphDRP/graphdrp_default_model.txt
Importing candle utils for pytorch
Initializing parameters

Traceback (most recent call last):
  File "/usr/local/GraphDRP/graphdrp_baseline_pytorch.py", line 263, in <module>
    main()
  File "/usr/local/GraphDRP/graphdrp_baseline_pytorch.py", line 256, in main
    gParameters = initialize_parameters()
  File "/usr/local/GraphDRP/graphdrp_baseline_pytorch.py", line 251, in initialize_parameters
    gParameters = candle.finalize_parameters(graphdrp_bmk)
  File "/opt/conda/lib/python3.7/site-packages/candle/parsing_utils.py", line 771, in finalize_parameters
    gParameters = args_overwrite_config(args, fileParameters)
  File "/opt/conda/lib/python3.7/site-packages/candle/parsing_utils.py", line 809, in args_overwrite_config
    params["output_dir"] = directory_from_parameters(params)
  File "/opt/conda/lib/python3.7/site-packages/candle/file_utils.py", line 185, in directory_from_parameters
    outdir = os.path.abspath(os.path.join(outdir, params["model_name"]))
KeyError: 'model_name'

**Comment by wilke** [comment]
Model issue but we need a demo model which works. Closing this for now.
